services:
  - type: web
    name: matclinics-rag-api
    runtime: python3.11
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
      python -m nltk.downloader punk